[pypi] upload to pypi automatically

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,29 +1,13 @@
 sudo: false
 
 os:
-  - osx
-  - linux
-
-#language: python
-
-#addons:
-#  apt:
-#    packages:
-#      - inkscape
-#      - libav-tools
-#      - gdb
-#      - mencoder
-#      - dvipng
-#      - libpng
-#      - gfortran
-#      - libatlas-dev
-#      - libatlas-base-dev
-#      - liblapack-dev
+- osx
+- linux
 
 cache:
   directories:
-     - $HOME/download/
-     - $HOME/install/
+  - "$HOME/download/"
+  - "$HOME/install/"
 
 env:
   - PYTHON_VERSION=2.7
@@ -31,41 +15,36 @@ env:
 
 before_install:
   - export CONDA_CACHED=1
-  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
-      export OS=Linux;
-    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-      export OS=MacOSX;
-    else
-      echo "OS not supported yet";
-      exit 1;
-    fi;
-  - if [[ $PYTHON_VERSION == "2.7" ]]; then
-      export MINICONDA=Miniconda;
-    elif [[ $PYTHON_VERSION == 3* ]]; then
-      export MINICONDA=Miniconda3;
-    else
-      echo "Could not find python version";
-      exit 1;
-    fi;
+  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OS=Linux; elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OS=MacOSX; else echo "OS not supported yet"; exit 1; fi;
+  - if [[ $PYTHON_VERSION == "2.7" ]]; 
+      then export MINICONDA=Miniconda; 
+    elif [[ $PYTHON_VERSION == 3* ]]; 
+      then export MINICONDA=Miniconda3; 
+    else echo "Could not find python version";exit 1; fi;
   - if [ ! -d $HOME/download/ ]; then mkdir $HOME/download/; fi;
   - if [ ! -d $HOME/install/ ]; then mkdir $HOME/install/; fi;
   - export MINICONDA_FILE=$MINICONDA-latest-$OS-x86_64-$PYTHON_VERSION
   - export MINCONDA_CACHE_FILE=$HOME/download/$MINICONDA_FILE.sh
   - export MINICONDA_INSTALL=$HOME/install/$MINICONDA_FILE
-  - if [ ! -f $MINCONDA_CACHE_FILE ]; then
-      export CONDA_CACHED=0;
-      wget http://repo.continuum.io/miniconda/$MINICONDA-latest-$OS-x86_64.sh -O $MINCONDA_CACHE_FILE;
-      bash $MINCONDA_CACHE_FILE -b -p $MINICONDA_INSTALL;
-    fi;
+  - if [ ! -f $MINCONDA_CACHE_FILE ]; then export CONDA_CACHED=0; wget http://repo.continuum.io/miniconda/$MINICONDA-latest-$OS-x86_64.sh -O $MINCONDA_CACHE_FILE; bash $MINCONDA_CACHE_FILE -b -p $MINICONDA_INSTALL; fi;
   - export PATH="$MINICONDA_INSTALL/bin:$PATH";
-  
+
 install:
-  - conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six matplotlib pillow;
+  - conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six matplotlib;
   - pip install codecov
   - python setup.py develop
-   
+
 script:
   - coverage run travis_tests.py
 
 after_success:
   - codecov
+
+deploy:
+  provider: pypi
+  user: maxz
+  password: 
+    secure: "vMEOlP7DQhFJ7hQAKtKC5hrJXFl5BkUt4nXdosWWiw//Kg8E+PPLg88XPI2gqIosir9wwgtbSBBbbwCxkM6uxRNMpoNR8Ixyv9fmSXp4rLl7bbBY768W7IRXKIBjpuEy2brQjoT+CwDDSzUkckHvuUjJDNRvUv8ab4P/qYO1LG4="
+  on:
+    plot_density
+  distributions: "bdist_wheel sdist sphinx_build sphinx_upload"
